export const LETTER_TEMPLATES = [
  {
    id: 'bankruptcy-misreporting',
    name: 'Bankruptcy Misreporting Letter',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau or Creditor Name]\n[Address] • [City, State ZIP]\n\nRe: Bankruptcy Misreporting – Account #[Account Number]\n\nTo Whom It May Concern:\n\nI obtained a bankruptcy discharge on [Discharge Date], yet this account still shows an outstanding balance. Under the Fair Credit Reporting Act (15 U.S.C. §1681), reporting a discharged debt as active is inaccurate and misleading. Please update the tradeline to reflect the discharge and a zero balance, or delete the entry within 30 days.\n\nI’ve enclosed a copy of the discharge for verification. Please send me written confirmation of the correction.\n\nThank you for your prompt attention.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito o Acreedor]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Reporte Incorrecto de Bancarrota – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nObtuve una descarga de bancarrota el [Fecha de Descarga], sin embargo esta cuenta aún muestra un saldo pendiente. Bajo la Ley de Reporte Justo de Crédito (15 U.S.C. §1681), reportar una deuda descargada como activa es incorrecto y engañoso. Favor de actualizar la línea de crédito para reflejar la descarga y un saldo de cero, o eliminen la entrada dentro de 30 días.\n\nAdjunto una copia de la descarga para su verificación. Por favor envíen confirmación por escrito de la corrección.\n\nGracias por su pronta atención.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'obsolete-debt',
    name: 'Obsolete Debt Letter',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Obsolete Debt – Account #[Account Number]\n\nTo Whom It May Concern:\n\nYour report lists the above account, which first became delinquent in [Month, Year]. Because more than seven years have passed, this debt is obsolete under the FCRA (15 U.S.C. §1681c). Please remove the entry and send written confirmation.\n\nRegards,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Deuda Obsoleta – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nSu informe muestra la cuenta mencionada, que se volvió morosa por primera vez en [Mes, Año]. Debido a que han pasado más de siete años, esta deuda es obsoleta bajo la FCRA (15 U.S.C. §1681c). Favor de eliminarla y enviar confirmación por escrito.\n\nSaludos cordiales,\n[Su Nombre]`
  },
  {
    id: 'second-round-dispute',
    name: 'Second Round Dispute (Escalation)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Second Dispute – Account #[Account Number]\n\nDear [Bureau],\n\nI previously disputed this account on [Date]. Your response repeated the same information without a proper reinvestigation, violating 15 U.S.C. §1681i. Please conduct a thorough investigation, provide the method of verification, and correct or delete the item within 15 days.\n\nPlease respond in writing.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Segunda Disputa – Cuenta #[Número de Cuenta]\n\nEstimados:\n\nAnteriormente disputé esta cuenta el [Fecha]. Su respuesta repitió la misma información sin una reinvestigación adecuada, violando 15 U.S.C. §1681i. Favor de realizar una investigación completa, proporcionar el método de verificación y corregir o eliminar el elemento dentro de 15 días.\n\nEspero respuesta por escrito.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'ag-cfpb-escalation',
    name: 'Attorney General / CFPB Escalation Draft',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau or Creditor Name]\n[Address] • [City, State ZIP]\n\nRe: Final Notice Before Regulatory Complaint – Account #[Account Number]\n\nTo Whom It May Concern:\n\nDespite prior disputes dated [Dates], the inaccurate reporting of the above account persists. Under FCRA and FDCPA provisions, you must ensure accuracy and furnish proper verification. If I do not receive a satisfactory response within 15 days, I will file formal complaints with the Consumer Financial Protection Bureau and my State Attorney General.\n\nI prefer to resolve this matter directly. Please send written confirmation of the correction.\n\nRegards,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito o Acreedor]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Último Aviso Antes de Queja Reguladora – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nA pesar de disputas previas fechadas [Fechas], continúa el reporte incorrecto de la cuenta mencionada. Bajo las disposiciones de la FCRA y la FDCPA, ustedes deben garantizar la exactitud y proporcionar verificación adecuada. Si no recibo respuesta satisfactoria en 15 días, presentaré quejas formales ante la Oficina de Protección Financiera del Consumidor y la Fiscalía General de mi estado.\n\nPrefiero resolver este asunto directamente. Favor de enviar confirmación por escrito de la corrección.\n\nSaludos,\n[Su Nombre]`
  },
  {
    id: '623-direct-dispute',
    name: '623 Direct Dispute Letter (FCRA §623)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Creditor or Debt Collector Name]\n[Address] • [City, State ZIP]\n\nRe: Direct Dispute – Account #[Account Number]\n\nTo Whom It May Concern:\n\nUnder FCRA §623(a)(8), I dispute the accuracy of the above account. The reported [specific inaccuracy] is incorrect. Please investigate, correct, or delete the information, and notify the credit bureaus within 30 days.\n\nEnclosed are copies of supporting documents.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre del Acreedor o Cobrador]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Disputa Directa – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nBajo FCRA §623(a)(8), disputo la exactitud de la cuenta mencionada. El [especificar error reportado] es incorrecto. Favor de investigar, corregir o eliminar la información y notificar a las agencias de crédito dentro de 30 días.\n\nAdjunto copias de documentos de respaldo.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: '611-general-dispute',
    name: '611 Dispute Letter (General Inaccuracy Dispute)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Dispute of Inaccurate Information – Account #[Account Number]\n\nTo Whom It May Concern:\n\nI dispute the accuracy of the above account. The report shows [describe error], which is unverified and misleading. Under FCRA §611, please investigate, correct, or delete this entry within 30 days and send me written confirmation.\n\nThank you,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Disputa por Información Inexacta – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nDisputo la exactitud de la cuenta mencionada. El informe muestra [describa el error], que es no verificado y engañoso. Bajo FCRA §611, favor de investigar, corregir o eliminar esta entrada dentro de 30 días y enviar confirmación por escrito.\n\nGracias,\n[Su Nombre]`
  },
  {
    id: 'method-of-verification',
    name: 'Method of Verification (MOV) Letter – FCRA §611(a)(7)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Request for Method of Verification – Account #[Account Number]\n\nDear [Bureau],\n\nYour recent response claims the disputed account was verified. Under FCRA §611(a)(7), please provide the method of verification, including the name and contact information of the entity you relied on. If you cannot supply this within 15 days, delete the entry and send confirmation.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Solicitud del Método de Verificación – Cuenta #[Número de Cuenta]\n\nEstimados:\n\nSu respuesta reciente afirma que la cuenta disputada fue verificada. Bajo FCRA §611(a)(7), favor de proporcionar el método de verificación, incluyendo el nombre y la información de contacto de la entidad usada. Si no pueden proporcionar esto en 15 días, eliminen la entrada y envíen confirmación.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'reinsertion-dispute',
    name: 'Reinsertion Dispute Letter – FCRA §611(a)(5)(B)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Unauthorized Reinsertion – Account #[Account Number]\n\nTo Whom It May Concern:\n\nThis account was previously deleted but has reappeared without the required notice. Under FCRA §611(a)(5)(B), you must provide written notice within 5 days of reinsertion. Please delete the entry again and confirm in writing.\n\nRegards,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Reinserción No Autorizada – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nEsta cuenta fue eliminada previamente pero ha reaparecido sin el aviso requerido. Bajo FCRA §611(a)(5)(B), ustedes deben proporcionar aviso por escrito dentro de 5 días de la reinserción. Favor de eliminarla nuevamente y confirmar por escrito.\n\nSaludos,\n[Su Nombre]`
  },
  {
    id: '609-disclosure',
    name: '609 Letter (Right to Disclosure)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Request for Disclosure – FCRA §609\n\nTo Whom It May Concern:\n\nUnder FCRA §609(a), I request a complete copy of my credit file, including all information sources and account details, particularly for the following accounts: [List Accounts]. Please provide these disclosures and any documentation used to verify the accounts.\n\nThank you,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Solicitud de Divulgación – FCRA §609\n\nA quien corresponda:\n\nBajo FCRA §609(a), solicito una copia completa de mi archivo de crédito, incluyendo todas las fuentes de información y detalles de las cuentas, especialmente para: [Lista de Cuentas]. Favor de proporcionar estas divulgaciones y cualquier documentación usada para verificar las cuentas.\n\nGracias,\n[Su Nombre]`
  },
  {
    id: 'personal-info-update',
    name: 'Personal Information Update Letter',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Credit Bureau Name]\n[Address] • [City, State ZIP]\n\nRe: Personal Information Update\n\nDear [Bureau],\n\nMy credit report lists incorrect personal information. Please remove/update the following:\n\n• Incorrect Address(es): [List]\n• Misspelled Name(s): [List]\n• Outdated Employer(s): [List]\n\nEnclosed are copies of my government ID and a utility bill verifying correct information. Kindly update your records and send confirmation.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre de la Agencia de Crédito]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Actualización de Información Personal\n\nEstimados:\n\nMi informe de crédito incluye información personal incorrecta. Favor de eliminar/actualizar lo siguiente:\n\n• Direcciones incorrectas: [Lista]\n• Nombres mal escritos: [Lista]\n• Empleadores desactualizados: [Lista]\n\nAdjunto copias de mi identificación oficial y un recibo de servicios para verificar la información correcta. Por favor actualicen sus registros y envíen confirmación.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'debt-validation',
    name: 'Debt Validation Letter (FDCPA §809)',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Debt Collector Name]\n[Address] • [City, State ZIP]\n\nRe: Debt Validation Request – Account #[Account Number]\n\nTo Whom It May Concern:\n\nUnder FDCPA §809, I request validation of the alleged debt. Please provide:\n\n1. Proof that you are authorized to collect.\n2. Full account statements and charge history.\n3. The name and address of the original creditor.\n\nCease collection activity until you provide this information. If you cannot validate, please delete any references to this debt and notify the credit bureaus.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre del Cobrador de Deuda]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Solicitud de Validación de Deuda – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nBajo FDCPA §809, solicito la validación de la supuesta deuda. Favor de proporcionar:\n\n1. Prueba de que están autorizados a cobrar.\n2. Extractos completos de la cuenta e historial de cargos.\n3. Nombre y dirección del acreedor original.\n\nDetengan toda actividad de cobro hasta que proporcionen esta información. Si no pueden validar, eliminen cualquier referencia a esta deuda y notifiquen a las agencias de crédito.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'cease-and-desist',
    name: 'Cease & Desist Letter (FDCPA §805(c))',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Debt Collector Name]\n[Address] • [City, State ZIP]\n\nRe: Cease and Desist – Account #[Account Number]\n\nTo Whom It May Concern:\n\nUnder FDCPA §805(c), I demand that you cease all telephone calls and collection activities regarding the above account. Any further contact must be in writing. Failure to comply may result in legal action.\n\nPlease confirm receipt.\n\nSincerely,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre del Cobrador de Deuda]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Carta de Cese y Desista – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nBajo FDCPA §805(c), exijo que cesen todas las llamadas telefónicas y actividades de cobro relacionadas con la cuenta mencionada. Cualquier contacto futuro debe ser por escrito. Si no cumplen, podría considerar acciones legales.\n\nFavor de confirmar recepción.\n\nAtentamente,\n[Su Nombre]`
  },
  {
    id: 'arbitration-election',
    name: 'Arbitration Election Letter',
    english: `[Your Name]\n[Address] • [City, State ZIP] • [Phone] • [Email]\n[Date]\n\n[Creditor or Debt Collector Name]\n[Address] • [City, State ZIP]\n\nRe: Election of Arbitration – Account #[Account Number]\n\nTo Whom It May Concern:\n\nPursuant to the arbitration clause in our agreement, I elect to resolve this matter through binding arbitration with [Arbitration Forum, e.g., AAA or JAMS]. Please provide the necessary instructions or cease collection efforts pending arbitration.\n\nI request all future communications be in writing.\n\nRegards,\n[Your Name]`,
    spanish: `[Su Nombre]\n[Dirección] • [Ciudad, Estado, Código Postal] • [Teléfono] • [Correo electrónico]\n[Fecha]\n\n[Nombre del Acreedor o Cobrador]\n[Dirección] • [Ciudad, Estado, Código Postal]\n\nAsunto: Elección de Arbitraje – Cuenta #[Número de Cuenta]\n\nA quien corresponda:\n\nDe acuerdo con la cláusula de arbitraje en nuestro contrato, elijo resolver este asunto mediante arbitraje vinculante con [Foro de Arbitraje, p. ej., AAA o JAMS]. Favor de proporcionar las instrucciones necesarias o cesen los esfuerzos de cobro mientras se tramita el arbitraje.\n\nSolicito que cualquier comunicación futura sea por escrito.\n\nSaludos cordiales,\n[Su Nombre]`
  }
];

export default LETTER_TEMPLATES;
