"""Dispute letter generator tuned for Metro-2 language.

All letters generated by this module must comply with the Evolv tone policy
defined in TONE_POLICY. This policy is enforced both in the template output
below and is exposed via get_dispute_system_prompt() for injection into any
LLM system prompt when this tool is used in an AI-assisted generation flow.
"""

from __future__ import annotations

from typing import Any, Iterable, Mapping

TONE_POLICY = (
    "You are drafting professional credit dispute letters. "
    "You MUST follow these rules strictly:\n"
    "1. Do NOT cite case law — no court case names, citations, or holdings.\n"
    "2. Do NOT cite statutes — no FCRA §, FDCPA §, 15 U.S.C. §, or any other code references.\n"
    "3. Do NOT include any threatening language — no mention of lawsuits, statutory damages, "
    "punitive damages, attorney's fees, or financial penalties.\n"
    "4. Do NOT use phrases like 'you are violating my rights' or 'I am aware of my rights'.\n"
    "5. Do NOT make the letter sound emotional, aggressive, or confrontational.\n"
    "6. Write in a calm, professional, fact-based tone — focus on requesting a factual "
    "reinvestigation or correction of specific inaccurate or unverifiable information."
)


def get_dispute_system_prompt() -> str:
    """Return the system prompt to inject into any LLM used for dispute letter drafting.

    Wire this into the system message of any AI model call that generates or
    refines dispute letter content. This ensures the tone policy is enforced
    at the model level, not just at the template level.
    """
    return TONE_POLICY


def generate_dispute_letter(
    violations: Iterable[Mapping[str, Any]],
    consumer: Mapping[str, Any],
    bureau: str,
) -> str:
    """Generate a dispute letter following the Evolv tone policy (TONE_POLICY).

    Output is calm, professional, and fact-based. It does not cite statutes,
    case law, or threats of legal action.
    """
    consumer_name = consumer.get("name", "Your Name")
    address = consumer.get("address", "Your Address")
    bureau_block = bureau or "Credit Bureau"
    violation_lines = []
    for violation in violations:
        code = violation.get("code") or violation.get("name") or "Violation"
        detail = violation.get("detail") or violation.get("description") or ""
        violation_lines.append(f"- {code}: {detail}")

    violation_text = "\n".join(violation_lines) or "- Pending audit details"

    return f"""
{consumer_name}
{address}

{bureau_block}

Re: Request for Reinvestigation of Inaccurate Account Information

To Whom It May Concern:

I am writing to request a reinvestigation of the following items, which I believe are inaccurate or unverifiable based on my records:

{violation_text}

I am asking that you conduct a thorough reinvestigation of each item listed above. If any of this information cannot be independently verified through documentation from the original furnisher, I am requesting that it be corrected or removed from my credit file.

Please provide the method of verification used, including the name and contact information of any furnisher relied upon. If you need any additional documentation from me, please notify me in writing.

Sincerely,
{consumer_name}
"""
